#!/bin/sh

context=""
kubeconfig=""
generator=""
node=""
namespace=""
cmd='[ "nsenter", "--target", "1", "--mount", "--uts", "--ipc", "--net", "--pid", "--", '
custom=false
if ! [ -p /dev/stdin ] && ! [ -p /dev/stdout ]; then
  tty=true
else
  tty=false
fi
while [ $# -gt 0 ]; do
  key="$1"

  case $key in
  --context)
    context="--context $2"
    shift
    shift
    ;;
  --kubecontext=*)
    context="--context=${key##*=}"
    shift
  ;;
  --kubeconfig)
    kubeconfig="--kubeconfig $2"
    shift
    shift
    ;;
  -n | --namespace)
    namespace="--namespace $2"
    shift
    shift
    ;;
  --namespace=*)
    namespace="--namespace=${key##*=}"
    shift
    ;;
  --)
    shift
    break
    ;;
  *)
    if [ -z "$node" ]; then
      node="$1"
      shift
    else
      echo "exactly one node required"
      exit 1
    fi
    ;;
  esac
done

while [ $# -gt 0 ]; do
  cmd="$cmd\"$1\", "
  custom=true
  shift
done
if [ "$custom" = true ]; then
  cmd="$(echo "$cmd" | awk '1' RS=', \n') ]"
else
  cmd="$cmd\"bash\", \"-l\" ]"
fi

if [ -z "$node" ]; then
  echo "Please specify node name"
  exit 1
fi

image="docker.io/library/alpine"
pod="nsenter-$(env LC_ALL=C tr -dc a-z0-9 < /dev/urandom | head -c 6)"

# Check the node
kubectl get node "$node" $context $kubeconfig >/dev/null || exit 1

overrides="$(
  cat <<EOT
{
  "spec": {
    "nodeName": "$node",
    "hostPID": true,
    "hostNetwork": true,
    "containers": [
      {
        "securityContext": {
          "privileged": true
        },
        "image": "$image",
        "name": "nsenter",
        "stdin": true,
        "stdinOnce": true,
        "tty": $tty,
        "command": $cmd
      }
    ],
    "tolerations": [
      {
        "key": "CriticalAddonsOnly",
        "operator": "Exists"
      },
      {
        "effect": "NoExecute",
        "operator": "Exists"
      }
    ]
  }
}
EOT
)"

# Support Kubectl <1.18
m=$(kubectl version --client -o yaml | awk -F'[ :"]+' '$2 == "minor" {print $3+0}' )
if [ "$m" -lt 18 ]; then
  generator="--generator=run-pod/v1"
fi

trap "EC=\$?; kubectl delete pod --wait=false $pod $context $kubeconfig $namespace 2>/dev/null; exit \$EC" EXIT INT TERM

echo "spawning \"$pod\" on \"$node\""
kubectl run --image "$image" --restart=Never --overrides="$overrides" -ti "$pod" $generator $context $kubeconfig $namespace
